type: books
books:
- id: configure-linux-kernel-fragments
  title: kernel fragments description
  description: null
  keywords: kernel fragments, kernel configuration, kernel optimization
  chapters:
  - url: configure-linux-kernel.md
    name: Introduction to Linux Kernel Configuration
    order: 1
  - url: 01-Disable_IPC_Timers_and_Audit.md
    name: 01 Disable IPC, Timers and Audit
    order: 2
  - url: 02-Disable_Kconfig_Scheduler_and_Initrd.md
    name: 02 Disable Kconfig, Scheduler and Initrd
    order: 3
  - url: 03-Disable_Perf_Profiling_and_Errata.md
    name: 03 Disable Perf, Profiling and Errata
    order: 4
  - url: 04-Disable_EFI_Power_Management_Debug_and_Energy_Model.md
    name: 04 Disable EFI, Power Management Debug and Energy Model
    order: 5
  - url: 05-Disable_Schedutil_CPUFreq_Governors_and_Virtualization.md
    name: 05 Disable Schedutil, CPUFreq Governors and Virtualization
    order: 6
  - url: 06-Disable_Kprobes_and_Jump_Labels.md
    name: 06 Disable Kprobes and Jump Labels
    order: 7
  - url: 07-Disable_GCC_Plugins_and_Function_Alignment.md
    name: 07 Disable GCC Plugins and Function Alignment
    order: 8
  - url: 08-Disable_Partition_Parsers.md
    name: 08 Disable Partition Parsers
    order: 9
  - url: 09-Enable_Inline_Spinlocks_and_Kernel_Operations.md
    name: 09 Enable Inline Spinlocks and Kernel Operations
    order: 10
  - url: 10-Disable_Swap_Memory_Hotplug_and_KSM.md
    name: 10 Disable Swap, Memory Hotplug and KSM
    order: 11
  - url: 11-Disable_Networking_IPv4_IPv6_Netfilter.md
    name: 11 Disable Networking IPv4, IPv6, Netfilter
    order: 12
  - url: 12-Disable_SCTP_VLAN_TIPC_BATMAN.md
    name: 12 Disable SCTP, VLAN, TIPC, BATMAN
    order: 13
  - url: 13-Disable_Wireless_Bluetooth_CAN_and_RFKILL.md
    name: 13 Disable Wireless, Bluetooth, CAN and RFKILL
    order: 14
  - url: 14-Disable_PCI_and_Firmware.md
    name: 14 Disable PCI and Firmware
    order: 15
  - url: 15-Disable_GNSS_and_ProcEvents.md
    name: 15 Disable GNSS and ProcEvents
    order: 16
  - url: 16-Disable_Block_Storage_NBD_and_AoE.md
    name: 16 Disable Block Storage NBD and AoE
    order: 17
  - url: 17-Disable_EEPROM_and_Misc_Drivers.md
    name: 17 Disable EEPROM and Misc Drivers
    order: 18
  - url: 18-Disable_Network_Device_Drivers.md
    name: 18 Disable Network Device Drivers
    order: 19
  - url: 19-Disable_PHY_Drivers.md
    name: 19 Disable PHY Drivers
    order: 20
  - url: 20-Disable_PPP_WLAN_Coexistence_and_Failover.md
    name: 20 Disable PPP, WLAN Coexistence, and Failover
    order: 21
  - url: 21-Disable_Input_Devices.md
    name: 21 Disable Input Devices
    order: 22
  - url: 22-Disable_Serial_TTY_and_TPM.md
    name: 22 Disable Serial, TTY and TPM
    order: 23
  - url: 23-Disable_I2C_Power_and_Sensor_Drivers.md
    name: 23 Disable I2C, Power and Sensor Drivers
    order: 24
  - url: 24-Disable_MFD_Display_and_Media_Drivers.md
    name: 24 Disable MFD, Display and Media Drivers
    order: 25
  - url: 25-Disable_USB_Sound_RTC_and_VirtIO.md
    name: 25 Disable USB, Sound, RTC and VirtIO
    order: 26
  - url: 26-Disable_Filesystem_Encodings_and_Compatibility.md
    name: 26 Disable Filesystem Encodings and Compatibility
    order: 27
  - url: 27-Enable_Minimal_Cryptographic_Core_with_SHA3_and_XTS.md
    name: 27 Enable Minimal Cryptographic Core with SHA3 and XTS
    order: 28
  - url: 28-Disable_Hardware_Cryptography_Keep_DRBG_and_Jitter_Entropy.md
    name: 28 Disable Hardware Cryptography, Keep DRBG and Jitter Entropy
    order: 29
  - url: 29-Disable_Kernel_Debugging_Features.md
    name: 29 Disable Kernel Debugging Features
    order: 30
  - url: 30-Disable_Filesystem_Verity_and_SecurityFS.md
    name: 30 Disable Filesystem Verity and SecurityFS
    order: 31
